import NextAuth from "next-auth/next";
import { Provider } from "next-auth/react";
import { connectToDatabae } from "../../../lib/db";
import CredentialsProvider from "next-auth/providers/credentials";

//the exported handler function is created by NextAuth, by calling NextAuth()
//paramter to configure NextAuth's behavior
export default NextAuth({
  session: {
    jwt: true,
  },
  providers: [
    CredentialsProvider({
      async authorize(credentials, req) {
        console.log("inside authorize");
        console.log("find existing user", credentials.email);
        console.log(credentials);
        const client = await connectToDatabae();

        const usersCollection = client.db().collection("users");
        console.log("find existing user", credentials.email);
        const user = await usersCollection.findOne({
          email: credentials.email,
        });
        if (!user) {
          console.log("User not found!");
          client.close();
          //when throw an error inside authorize(), promise will be rejected, and it will then redirect to client to other page
          throw new Error("No user found!");
        }

        console.log("User is found, then verify password");
        const isValid = await verifyPassword(
          credentials.password,
          user.password
        );
        console.log("isValid:", isValid);
        if (!isValid) {
          throw new Error("Could not log you in!");
          client.close();
        }

        client.close();
        //when return an object inside authorize(), that means authorization succeed

        console.log("returning object");
        return { email: user.email };
      },
    }),
  ],
});
